services:
  - type: web
    name: Tripverse-server
    runtime: docker
    repo: https://github.com/sameeraherath/Tripverse---the-universe-of-travel-stories..git
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000


